// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpertEducation.GestaoConteudo.Data;

#nullable disable

namespace XpertEducation.GestaoConteudo.Data.Migrations
{
    [DbContext(typeof(GestaoConteudoContext))]
    [Migration("20251126184121_AddConteudoProgramatico")]
    partial class AddConteudoProgramatico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConteudoAula")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Aula", b =>
                {
                    b.HasOne("XpertEducation.GestaoConteudo.Domain.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Curso", b =>
                {
                    b.OwnsOne("XpertEducation.GestaoConteudo.Domain.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bibliografia")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Bibliografia");

                            b1.Property<string>("Conteudo")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Conteudo");

                            b1.Property<string>("Metodologia")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Metodologia");

                            b1.Property<string>("Objetivo")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Objetivo");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("ConteudoProgramatico");
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Curso", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
