// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpertEducation.GestaoConteudo.Data;

#nullable disable

namespace XpertEducation.GestaoConteudo.Data.Migrations
{
    [DbContext(typeof(GestaoConteudoContext))]
    [Migration("20250929020722_CreateGestaoConteudo")]
    partial class CreateGestaoConteudo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConteudoAula")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Curso", b =>
                {
                    b.HasOne("XpertEducation.GestaoConteudo.Domain.Aula", "Aula")
                        .WithMany("Cursos")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("XpertEducation.GestaoConteudo.Domain.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bibliografia")
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Conteudo")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Conteudo");

                            b1.Property<string>("Metodologia")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Metodologia");

                            b1.Property<string>("Objetivo")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Objetivo");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("Aula");

                    b.Navigation("ConteudoProgramatico")
                        .IsRequired();
                });

            modelBuilder.Entity("XpertEducation.GestaoConteudo.Domain.Aula", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
