// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpertEducation.GestaoAlunos.Data;

#nullable disable

namespace XpertEducation.GestaoAlunos.Data.Migrations
{
    [DbContext(typeof(GestaoAlunosContext))]
    [Migration("20251015031855_UpdateHistoricoAprendizado")]
    partial class UpdateHistoricoAprendizado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Certificado");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.HistoricoAprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("HistoricosAprendizados");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatriculaStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Certificado", b =>
                {
                    b.HasOne("XpertEducation.GestaoAlunos.Domain.Models.Aluno", null)
                        .WithMany("Certificados")
                        .HasForeignKey("AlunoId");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.HistoricoAprendizado", b =>
                {
                    b.HasOne("XpertEducation.GestaoAlunos.Domain.Models.Aluno", "Aluno")
                        .WithMany("HistoricoAprendizado")
                        .HasForeignKey("AlunoId")
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Matricula", b =>
                {
                    b.HasOne("XpertEducation.GestaoAlunos.Domain.Models.Aluno", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .IsRequired();
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Models.Aluno", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("HistoricoAprendizado");

                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
