// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpertEducation.GestaoAlunos.Data;

#nullable disable

namespace XpertEducation.GestaoAlunos.Data.Migrations
{
    [DbContext(typeof(AlunosContext))]
    partial class AlunosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Matricula", b =>
                {
                    b.HasOne("XpertEducation.GestaoAlunos.Domain.Aluno", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId");
                });

            modelBuilder.Entity("XpertEducation.GestaoAlunos.Domain.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
